### PR TITLE
Maid 1149 split cache and config. Fixes #174

### LINKED ISSUE #174: Bootstrap file's hardcoded endpoints section is erased
I ran a Client example with a bootstrap file containing the following at the start:

```
{
  "preferred_port": {
    "variant": "Tcp",
    "fields": [
      5483
    ]
  },
  "hard_coded_contacts": [
    {
      "endpoint": "45.55.207.180:5483"
    },
    {
      "endpoint": "178.62.7.96:5483"
    },
    {
      "endpoint": "128.199.199.210:5483"
    },
    {
      "endpoint": "37.59.98.1:5483"
    },
    {
      "endpoint": "45.79.93.11:5483"
    },
    {
      "endpoint": "45.79.2.52:5483"
    },
  ],
  "contacts": [
    {
      "endpoint": "45.55.207.180:5483"
    },
    {
      "endpoint": "178.62.7.96:5483"
    },
    {
      "endpoint": "128.199.199.210:5483"
    },
    {
      "endpoint": "37.59.98.1:5483"
    },
    {
      "endpoint": "45.79.93.11:5483"
    },
    {
      "endpoint": "45.79.2.52:5483"
    },
  ]
}
```

After the example ran, it contained:
```
{
  "preferred_port": {
    "variant": "Tcp",
    "fields": [
      0
    ]
  },
  "hard_coded_contacts": [],
  "contacts": [
    {
      "endpoint": "127.0.0.1:48660"
    },
    {
      "endpoint": "192.168.1.65:48660"
    },
    {
      "endpoint": "[::1]:48660"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/180)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ned14

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ned14** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[installer/crust_peer.config, line 27 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/180#-Ju5gqY4A9wbUVmysoPj)** ([raw file](https://github.com/maidsafe/crust/blob/c1a42a73a8c5fd091aa2bbda7d8846e7ac701de5/installer/crust_peer.config#L27)):</sup>
Are these "official"? I'm just wondering about CI testing, CI success or fail could get confounded by other tests happening.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/180)

**Comment by chandraprakash** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[installer/crust_peer.config, line 27 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/180#-Ju5gqY4A9wbUVmysoPj)** ([raw file](https://github.com/maidsafe/crust/blob/c1a42a73a8c5fd091aa2bbda7d8846e7ac701de5/installer/crust_peer.config#L27)):</sup>
They are the endpoints of the droplets and they serve as a sample config, which (Vault and client) installers needs to include.
I will rename them to sample.config to make them explicit. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/180)

**Comment by ned14** [comment]
Reviewed 1 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/180)

**Comment by ned14** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/180)

**Comment by ned14** [comment]
Reviewed 6 of 6 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/180)

**Pull request merged**
