### PR TITLE
Win freeze

### PR DESCRIPTION
**Pull request by inetic**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/400)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by inetic** [comment]
fixes #393

**Comment by vinipsmaker** [comment]
So the problem was in the test and not on our code?

**Comment by inetic** [comment]
Depends on what you mean by "our code" :), but yes, the thread in that test never finished. My theory is that we've had this bug there a long time but perhaps something changed on the test machines which made them freeze.

**Comment by Viv-Rajkumar** [comment]
:+1: nice one @inetic

**Comment by canndrew** [comment]
Looks like these commits conflict a bit with the [fix file handling](https://github.com/maidsafe/crust/pull/380) PR.

**Comment by inetic** [comment]
@canndrew yes, sorry about that, I needed to debug/print the location of the cache file and it was very hard to do with [this code](https://github.com/maidsafe/crust/pull/380/files#diff-dd722105e2a87507c27621ae03272916L78), it already bugged me for some time so I just changed it.

**Pull request merged**
