### PR TITLE
refactor/connect: redo connect and hole punch

### PR DESCRIPTION
**Pull request by ustulation**
Rewrite entire logic to connect to peer. Existing code was convoluted and error prone and huge amount of extra code which is completely unnecessary.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/769)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
Reviewed 8 of 15 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/769)*

**Pull request merged**
