### PR TITLE
Send bootstrap accept

### PR DESCRIPTION
**Pull request by Fraser999**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/527)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Please cherry-pick this commit: https://github.com/maidsafe/crust/commit/3bfafbdab0686398003696459245ced44641e1ed

**Comment by Viv-Rajkumar** [comment]
@vinipsmaker you mind raising the commit you linked in a separate PR? just so @canndrew can review that separately while this stuff from today and before gets merged in.

**Comment by vinipsmaker** [comment]
> @vinipsmaker you mind raising the commit you linked in a separate PR? just so @canndrew can review that separately while this stuff from today and before gets merged in.

I can if you really like. The commit I mentioned was raised before @Fraser999 submitted this PR, but that's not the reason why I asked him to cherry-pick the mentioned commit. The reason I requested him to cherry-pick the mentioned commit is because the mentioned commit fixes an issue that was introduced in commit https://github.com/Fraser999/crust/commit/ca7cedbbf12965263b301137494fcb665f434c38 (which is the base for this whole PR).

**Comment by vinipsmaker** [comment]
You can view the commit https://github.com/maidsafe/crust/commit/3bfafbdab0686398003696459245ced44641e1ed as a continuation of commit https://github.com/Fraser999/crust/commit/ca7cedbbf12965263b301137494fcb665f434c38. Also, it's a commit with few changes, so it shouldn't pose a problem. Anyway, I'll leave judgment at your call. I think I raised my points already.

**Comment by Viv-Rajkumar** [comment]
nw @vinipsmaker it's been merged in now.

**Comment by Viv-Rajkumar** [comment]
Reviewed 3 of 12 files at r1, 3 of 12 files at r2, 1 of 6 files at r3, 3 of 7 files at r4, 3 of 6 files at r6, 2 of 2 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/527)*

**Pull request merged**
