### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by vinipsmaker**
r? @afck

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/629)

### CODE REVIEW

**Comment by afck** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/connection.rs, line 209 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/629#-KDieuVFdI4T2nI8zS8f:-KDieuVGyj3-cPLwX4BA:-1044363147) ([raw file](https://github.com/maidsafe/crust/blob/e07e54947c302ae9019d96edc8ea29f63b64b912/src/connection.rs#L209)):*
These lines should not be needed if the conversion function would work correctly, since `deadline > now`. (See below.)

---

*[src/util.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/629#-KDifASgMBKo7uhzH3nv:-KDifAShopnv_6UHs9BC:1542146510) ([raw file](https://github.com/maidsafe/crust/blob/e07e54947c302ae9019d96edc8ea29f63b64b912/src/util.rs#L28)):*
If you match `(dur - Duration::seconds(secs)).num_nanoseconds()` instead of subtracting that inside, this will never be `None` and the result will be exact to the nanosecond.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/629)*

**Comment by afck** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/util.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/629#-KDifASgMBKo7uhzH3nv:-KDiiv6tdNWwGZC_j2tl:-1548947178) ([raw file](https://github.com/maidsafe/crust/blob/e07e54947c302ae9019d96edc8ea29f63b64b912/src/util.rs#L28)):*
I wouldn't even do the checks for `< 0` now anymore. Without them, it should just always produce the `Duration` with the exact same two values for `seconds` and `nanoseconds`, regardless of whether they are positive or negative.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/629)*

**Comment by afck** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/629)*

**Comment by vinipsmaker** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/connection.rs, line 209 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/629#-KDieuVFdI4T2nI8zS8f:-KDxRBcSbKIDMgCR5TSU:-499146009) ([raw file](https://github.com/maidsafe/crust/blob/e07e54947c302ae9019d96edc8ea29f63b64b912/src/connection.rs#L209)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/629)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/629)*

**Pull request merged**
