### PR TITLE
Clean bootstrap cache in tests

### LINKED ISSUE #395: Bootstrap cache makes tests non deterministic
E.g. the `service::bootstrap` test expects the bootstrap to finish within 5 seconds, if however there has been a bootstrap.cache file created from previous tests *and* the endpoint of the testing peer is not at the beginning of the cache list, the test fails due to timeout.

To reproduce this, run

```
cargo test # creates the ~/.config/.../...bootstrap.cache file
cargo test service -- --nocapture
```

The first test `service::bootstrap` will fail.

### PR DESCRIPTION
**Pull request by inetic**
This PR is blocked by https://github.com/maidsafe/crust/pull/390
and fixes #395

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/396)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Test is hanging on Windows.

**Comment by vinipsmaker** [comment]
It's not blocked anymore, but [hanging commit found its way into `master`](https://ci.appveyor.com/project/MaidSafe-QA/crust/build/1.0.353/job/g6yax1h2a5i7okp8).

**Comment by inetic** [comment]
@vinipsmaker my assumption is that it is the same issue as this one: https://github.com/maidsafe/crust/issues/393

**Pull request merged**
