### PR TITLE
Fix for first node doesn't read its own bootstrap list

### LINKED ISSUE #134: First node doesn't read its own bootstrap list
When running the crust_peer example, if the node is the first on the LAN (i.e. it manages to start listening on the beacon port and doesn't connect to any other nodes via the beaconing method) then it disregards its own bootstrap list.

### PR DESCRIPTION
**Pull request by chandraprakash**
Also added a crude fix not bootstrapping off own listening ports by removing own listening endpoints just before bootstrapping.  Fixes  #134 

I will do a separate PR to clean up.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/135)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ned14

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
? @dirvine

**Comment by dirvine** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[docs/bootstrap.md, line 4 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-Jrc_oZRmLKxdFjhAZcw)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/docs/bootstrap.md#L4)):</sup>
Is this correct, is it not in the directory the exe is run from (work dir)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Comment by Fraser999** [comment]
Just for info: this works across two droplets.

**Comment by dirvine** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[docs/bootstrap.md, line 18 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-Jrca-JGMKdDgz6kVlxH)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/docs/bootstrap.md#L18)):</sup>
Also useful and required for folks who want to port forward their router (i.e. run tcp node at home). It is less safe though as you will always connect to the network on the same ports, but this is potentially a very small security issue and not of concern to many. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Comment by dirvine** [comment]
Review status: 1 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.
Reviewed files:
- src/bootstrap_handler.rs @ r1

---

<sup>**[src/connection_manager.rs, line 193 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-JrcaaHS7KUERjYuDq1E)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/src/connection_manager.rs#L193)):</sup>
Would it not need to be `pub` then 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Comment by dirvine** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.
Reviewed files:
- src/connection_manager.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Comment by chandraprakash** [comment]
Review status: 2 of 3 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[docs/bootstrap.md, line 4 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-Jrc_oZRmLKxdFjhAZcw)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/docs/bootstrap.md#L4)):</sup>
Work dir actually, I will update it

---

<sup>**[docs/bootstrap.md, line 18 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-Jrca-JGMKdDgz6kVlxH)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/docs/bootstrap.md#L18)):</sup>
added

---

<sup>**[src/connection_manager.rs, line 193 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/135#-JrcaaHS7KUERjYuDq1E)** ([raw file](https://github.com/maidsafe/crust/blob/17b42e0001e866bea371b7501c220b0426eb3e3a/src/connection_manager.rs#L193)):</sup>
Yeah later we need to make it public.  Still its old API we are supporting. So trying not to confuse in this version.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Comment by dirvine** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- docs/bootstrap.md @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/135)

**Pull request merged**
