### PR TITLE
feat/stun: integrate stun into listener

### PR DESCRIPTION
**Pull request by ustulation**
Let TCP listener also function as STUN/Echo server

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/758)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 8 of 9 files at r1, 1 of 3 files at r2.
Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/758)*

**Comment by dirvine** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/758)*

**Pull request merged**
