### PR TITLE
Parallelise Service::connect function

### PR DESCRIPTION
**Pull request by canndrew**
Make the `Service::connect` function try all it's connection methods in parallel.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/591)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/591)*

**Comment by vinipsmaker** [comment]
> This branch is out-of-date with the base branch

**Comment by canndrew** [comment]
@vinipsmaker rebased and ready to rock.

**Pull request closed without merging**
