### PR TITLE
Bootstrap black list

### PR DESCRIPTION
**Pull request by ustulation**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/755)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bootstrap/mod.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/755#-KJp14qNvkMkc7iHJkMB:-KJp14qOQ4z8vg0yMiSK:-223790780) ([raw file](https://github.com/maidsafe/crust/blob/4a864fb5890dcaa88c38d54eaec4af59d78d2ef0/src/bootstrap/mod.rs#L142)):*
> ```Rust
>         while let Some(avoid) = self.blacklist.pop() {
>             peers.retain(|addr| addr.0 != avoid);
>         }
> ```

A single call `peers.retain(|addr| !self.blacklist.contains(addr))` would suffice here. Since `Vec::contains` is `O(n)`, though, it might make sense to take the blacklist as a `HashSet` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/755)*

**Comment by ustulation** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bootstrap/mod.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/755#-KJp14qNvkMkc7iHJkMB:-KJp7L22EAFvRVBp2s0P:144624694) ([raw file](https://github.com/maidsafe/crust/blob/4a864fb5890dcaa88c38d54eaec4af59d78d2ef0/src/bootstrap/mod.rs#L142)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> A single call `peers.retain(|addr| !self.blacklist.contains(addr))` would suffice here. Since `Vec::contains` is `O(n)`, though, it might make sense to take the blacklist as a `HashSet` instead.
</details>
Done - used a hashset instead now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/755)*

**Comment by afck** [comment]
Reviewed 8 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/755)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/755)*

**Comment by afck** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/755)*

**Pull request merged**
