### PR TITLE
Maid 1125 bootstrap handler

### PR DESCRIPTION
**Pull request by chandraprakash**
Need to clean-up code and document the behaviour.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/130)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ned14

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
This should not be passed to review when marked as WIP. Please eiher close and fix or rename and create another PR for documentation 

---

Review status: 0 of 5 files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
There are definitely a few things I need clarified before I can okay the merge

---

Review status: 0 of 5 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[src/beacon.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpAtsYZxotoTvif84)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/beacon.rs#L38)):</sup>
Commented out stuff will need to be removed before merge

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
Surely should be a Port instead of u16 so we can disambiguate TCP vs UTP? Unless this is the beacon port? If it is the beacon port, this should be called "preferred_beacon_port"

---

<sup>**[src/bootstrap_handler.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWq-2tQOz7pb3ZOcMN)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L108)):</sup>
Agreed, Result with the error is much nicer so any file we can't open can be reported

---

<sup>**[src/bootstrap_handler.rs, line 183 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWqZ-o82GM0l2L-Ga0)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L183)):</sup>
Indentation?

---

<sup>**[src/connection_manager.rs, line 107 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWsGeM4H8_mee8m64X)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/connection_manager.rs#L107)):</sup>
I'm a bit confused here. Why is Contacts no longer keeping a crypto key?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
Review status: all files reviewed, 5 unresolved discussions, some commit checks failed.
Reviewed files:
- src/beacon.rs @ r1
- src/bootstrap_handler.rs @ r1
- src/connection_manager.rs @ r1
- src/lib.rs @ r1
- src/transport.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by chandraprakash** [comment]
I am yet to do clean up of the code before it can be merged. The Jira task MAID-1125 is currently in progress. I will now do the cleanup and remove the WIP title soon after that.

---

Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/beacon.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpAtsYZxotoTvif84)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/beacon.rs#L38)):</sup>
I will remove them.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
For simplicity, I kept it common for all protocol. 
Crust will try to start listening on this port on all supported protocols

---

<sup>**[src/connection_manager.rs, line 107 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWsGeM4H8_mee8m64X)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/connection_manager.rs#L107)):</sup>
Crust currently doesn't support encryption. So, IMO no point having it in a configuration file.
It can now easily added when we start supporting it. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
Review status: all files reviewed, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
crust keeps its protocols one per port randomly assigned. I think you mean the beacon here surely? That's protocol neutral.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by chandraprakash** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
Sorry, I didn't mean beacon port. 
We need to start some crust nodes on fixed ports. This is to host nodes on droplets on fixed ports.
Idea is to pack these hard coded endpoints in the installers as a part of bootstrap file. So that folks can fall back to these nodes if they fail to connect to network by other default methods.
We can certainly add more to the file and be specific about the protocols. But I guess it can be done at later stage.  I took simpler approach to say same port number for all protocol.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
Ok, but when the rust-utp support lands it'll break quite badly. Trying to speak TCP to a UTP port or vice versa won't work well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by dirvine** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
Yes we do need to identify the protocol, unless we are saying these hard coded endpoints are always tcp (reasonable). Seems though the flexibility of a Port may be better suited.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.
Reviewed files:
- src/beacon.rs @ r1
- src/bootstrap_handler.rs @ r1
- src/connection_manager.rs @ r1
- src/lib.rs @ r1
- src/transport.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by ned14** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- src/beacon.rs @ r2
- src/bootstrap.rs @ r2
- src/bootstrap_handler.rs @ r2
- src/connection_manager.rs @ r2
- src/lib.rs @ r2
- src/transport.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Comment by chandraprakash** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/bootstrap_handler.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/130#-JrWpRSfWJGTMFOM_7FW)** ([raw file](https://github.com/maidsafe/crust/blob/e8c8b2170ed160fb2fce35c134e7cc0b97ef6c85/src/bootstrap_handler.rs#L38)):</sup>
Agreed, updated to Port now :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/130)

**Pull request merged**
