### PR TITLE
Start listening on ports specified in the config file

### PR DESCRIPTION
**Pull request by inetic**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/282)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by inetic** [comment]
Eh, @vinipsmaker, pls hold on with merging, I found few more changes that need to go to this PR.

**Comment by inetic** [comment]
@fixes 283

**Comment by vinipsmaker** [comment]
Build is failing.

I "cooked" a fix if you're interested: https://github.com/vinipsmaker/crust/commit/c6facc88cf9bae91ab2b879491bb535de04d49e1

**Comment by vinipsmaker** [comment]
Apart from that, code looks okay and should be merged.

**Comment by inetic** [comment]
Thanks, cherry picked your commit into this branch.

**Comment by vinipsmaker** [comment]
> I cherry picked your commit

Great, I thought you guys only liked to use `merge`. I don't remember the last time I saw `rebase` around here. ;-)

**Comment by dirvine** [comment]
We're sneaky :-)

**Pull request merged**
