### PR TITLE
Fix 342

### PR DESCRIPTION
**Pull request by vinipsmaker**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/347)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
I managed to reproduce the failure under OS X after **many** attempts (a script helped):

```
running 1 test
thread 'service::test::network' panicked at 'assertion failed: `(left == right)` (left: `89`, right: `90`)', src/service.rs:632
stack backtrace:
   1:        0x100c90eb8 - sys::backtrace::tracing::imp::write::h2a3c1b1b2302b0b0W5s
   2:        0x100c9299f - panicking::log_panic::closure.38918
   3:        0x100c92449 - panicking::log_panic::h9fdebde30b454fb57Uw
   4:        0x100c7f356 - sys_common::unwind::begin_unwind_inner::hd85c5bc2336b01e6u8r
   5:        0x100c7f73e - sys_common::unwind::begin_unwind_fmt::h85dfaddf9453fbf9A7r
   6:        0x1009363e8 - service::test::network::hf8e7e90ab9d1bca0xNa
   7:        0x100ad63fb - boxed::F.FnBox<A>::call_box::h12977869192127095420
   8:        0x100ad8b4d - boxed::F.FnBox<A>::call_box::h18299346003033972753
   9:        0x100ad6d52 - sys_common::unwind::try::try_fn::h18338635074201241737
  10:        0x100c90388 - __rust_try
  11:        0x100c8d88e - sys_common::unwind::try::inner_try::hf5e2692092f7fc4d24r
  12:        0x100ad6f02 - boxed::F.FnBox<A>::call_box::h7075346960086663229
  13:        0x100c91d6d - sys::thread::Thread::new::thread_start::hb7711a4a72b477fdnsw
  14:     0x7fff92200059 - _pthread_body
  15:     0x7fff921fffd6 - _pthread_start
test service::test::network ... FAILED

failures:

failures:
    service::test::network

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Most of the time, instead hanging, the test finished even before the timeout had the chance to show up. Maybe the `thread::sleep_ms` is helping to avoid a possible race?

**Comment by inetic** [comment]
Out of curiosity, how many times do you have to run it on average to reproduce it?

**Comment by vinipsmaker** [comment]
> Out of curiosity, how many times do you have to run it on average to reproduce it?

I used a script. Maybe 100 times.

**Comment by vinipsmaker** [comment]
@inetic found the race and I pulled the change.

Removing the "WIP" tag. This PR is ready.

I'll create another one to pursue the Windows problem.

**Pull request merged**
