### PR TITLE
Minor fixups. Use quick_error for Error type.

### PR DESCRIPTION
**Pull request by canndrew**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/625)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
> This branch is out-of-date with the base branch

**Comment by canndrew** [comment]
Sorry, I forgot about this one. Updated.

**Comment by vinipsmaker** [comment]
Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/625)*

**Pull request merged**
