### PR TITLE
Version change to 0.5.0

### PR DESCRIPTION
**Pull request by vinipsmaker**
r? @Viv-Rajkumar

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/387)

### CODE REVIEW

**Comment by inetic** [comment]
It's been decided to wait for the following fixes:
* Thread panic at the end of windows [CI tests](https://ci.appveyor.com/project/MaidSafe-QA/crust/build/1.0.344/job/lcqw6inskpkwq0r7) (not reported as failure but can be seen in output).
* Fix to #382. For this one PR #390 should fix it but has not yet been reviewed.
* There is also this issue: https://github.com/maidsafe/crust/issues/388 but I would vote to not wait for that one because it might be a hard one.

**Comment by inetic** [comment]
Added issue for the "thread panic at the end of windows CI test here https://github.com/maidsafe/crust/issues/393

**Comment by vinipsmaker** [comment]
Now only #388 is missing

**Comment by vinipsmaker** [comment]
Don't merge now, I'll update the changelog

**Comment by vinipsmaker** [comment]
Okay, you can merge now.

**Pull request merged**
