### PR TITLE
Improve uTP

### PR DESCRIPTION
**Pull request by vinipsmaker**
This updates #439 by adding more protection on the crust side of things. To close the issue for good, updates are also required on the rust-utp side.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/445)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
could you link the required rust-utp updates as well ?
also, a detailed test report of the failure rate before and after this update will be preferred to be included as well.
otherwise it will be hard to tell whether this update is necessary.

Also, the PR https://github.com/maidsafe/crust/pull/442 is preferred to be merged before this PR,
as the testing code of network using utp is in that one.

**Comment by vinipsmaker** [comment]
> could you link the required rust-utp updates as well ?

I started working on this after I submitted this PR. The idea is to not leave crust in a so bad situation while we fix the real issue within rust-utp.

> also, a detailed test report of the failure rate before and after this update will be preferred to be included as well.

Well, the current issues won't happen because if rust-utp misbehave, crust will issue a "connection loss" event. We "just" exchange one error for another. Connection loss is expected in the wild and layers above crust will have to handle them anyway. With the patch, they'll have the chance to not hang thanks to misbehaving rust-utp.

**Comment by maqi** [comment]
>> could you link the required rust-utp updates as well ?

>I started working on this after I submitted this PR. The idea is to not leave crust in a so bad situation while we fix the real issue within rust-utp.

If so, I will prefer merge your rust-utp work first then merge this PR, or merge them at the same time.

>> also, a detailed test report of the failure rate before and after this update will be preferred to be included as well.

>Well, the current issues won't happen because if rust-utp misbehave, crust will issue a "connection loss" event. We "just" exchange one error for another. Connection loss is expected in the wild and layers above crust will have to handle them anyway. With the patch, they'll have the chance to not hang thanks to misbehaving rust-utp.

However, the current crust network test only covers TCP, and this`promised behaviour` is not tested. It is good crust raise a connection loss instead of just hanging, but we need a report here of such failing rate is acceptable.

**Pull request closed without merging**
