### PR TITLE
docs/update: add more detail to README and update links

### LINKED ISSUE #744: License wrong in README and Cargo.toml
The license image in the README says gpl3 (at the top), and on crates.io as well, but the actual `LICENSE` appears to be some commercial license.

### PR DESCRIPTION
**Pull request by Fraser999**
This adds license and contribution paragraphs to the README and also updates changed URLs.

Fixes #744

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/748)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/748)*

**Comment by Kerosene2000** [comment]
Not properly working: http://docs.maidsafe.net/crust/latest is offline

**Comment by dirvine** [comment]
thanks @Kerosene2000  It was a DNS issue, all OK now I think.

**Pull request merged**
