### PR TITLE
Fix #539

### LINKED ISSUE #539: Send only one `NewPeer` per peer.
Make sure Crust sends only one `NewPeer` event per peer.
I already partially implemented this for the TCP-only version: https://github.com/afck/crust/commit/24f34d237b2549a0223e347f4486ba24c4b02337

### PR DESCRIPTION
**Pull request by vinipsmaker**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/553)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/553)*

**Comment by vinipsmaker** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/553)*

**Pull request merged**
