### PR TITLE
Fix #540

### LINKED ISSUE #540: Check peer keys on connect.
I already partially implemented this for the TCP-only version:
https://github.com/afck/crust/commit/df9b69871dc65508a2d1cf26a7f8df9e9a4f108c

### PR DESCRIPTION
**Pull request by canndrew**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/545)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
This has been rebased off of the newly-rebased service-test-changes branch.

**Comment by vinipsmaker** [comment]
It needs to be rebased. It contains commits that were merged in master already.

**Comment by vinipsmaker** [comment]
Continuing it in https://github.com/maidsafe/crust/pull/552

**Pull request closed without merging**
