### PR TITLE
Fixes nightly build error

### PR DESCRIPTION
**Pull request by chandraprakash**
Using net2 crates to use `net2::UdpSocketExt` trait

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/245)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
Looks like CI script need to be updated to use latest nightly. @Fraser999 
It should build okay with `rustc 1.4.0-nightly (e2bebf32f 2015-08-14)`

**Comment by Viv-Rajkumar** [comment]
@chandraprakash are you referring to the CI script for Travis or Jenkins here having the issue? seems like travis in linux is fine but not for osx...

**Comment by chandraprakash** [comment]
Yes Travis osx is using `rustc 1.4.0-nightly (021389f6a 2015-08-13)`
I think even Jenkins on windows was also using old version. I guess fraser triggered a rebuild

**Comment by Fraser999** [comment]
I've manually updated the Windows slaves and the test is re-running there.

For OS X with Travis, it's using a very slightly older version of Rust.  I guess if you're happy with the failing OS X build and it passes on Linux and Windows with latest Rust then you're good to merge.

If you're not happy, we can wait for a few hours or a day and re-trigger the Travis builds hoping that OS X for Travis has been updated by then.

**Comment by Viv-Rajkumar** [comment]
@Fraser999 can we try a rebuild on travis OSX now please. I just upgraded my nightly in OSX and have got 
> Vivs-MacBook-Pro:crust viv$ rustc --version
rustc 1.4.0-nightly (e2bebf32f 2015-08-14)

**Pull request merged**
