### PR TITLE
updated config file sample

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/247)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[installer/sample.config, line 30 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/247#-Jx0r3ADhtIk1_EXNdeO)** ([raw file](https://github.com/maidsafe/crust/blob/6826088ca3b615bd68d82c4945d831084a8d3d51/installer/sample.config#L30)):</sup>
Why this change? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/247)

**Comment by chandraprakash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[installer/sample.config, line 30 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/247#-Jx0r3ADhtIk1_EXNdeO)** ([raw file](https://github.com/maidsafe/crust/blob/6826088ca3b615bd68d82c4945d831084a8d3d51/installer/sample.config#L30)):</sup>
As this is just a sample config and this can be used with crust based examples also.
I changed it to avoid interference with routing/vault network. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/247)

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[installer/sample.config, line 2 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/247#-Jx5vIlb0IresqIY1KKX)** ([raw file](https://github.com/maidsafe/crust/blob/2a84dafc578b235f87b0d4c7c2762ebdc0996b6d/installer/sample.config#L2)):</sup>
Can you please explain this and also the change of default beacon_port? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/247)

**Comment by chandraprakash** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[installer/sample.config, line 2 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/247#-Jx5vIlb0IresqIY1KKX)** ([raw file](https://github.com/maidsafe/crust/blob/2a84dafc578b235f87b0d4c7c2762ebdc0996b6d/installer/sample.config#L2)):</sup>
If override_default_bootstrap field is false, all the default bootstrapping methods will be enabled including hard_coded_contacts.
If it is set to true, only hard_coded_contacts will be used for bootstrapping. 

Default beacon_port is still 5483 (https://github.com/maidsafe/crust/blob/master/src/config_utils.rs#L47)

As this is just a sample config and this can be used with crust based examples also.
I changed it to avoid interference with routing/vault network. 

Will change sample beacon_port back to 5483 to avoid any confusions. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/247)

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/247)

**Pull request merged**
