### PR TITLE
Use only TCP for now.

### PR DESCRIPTION
**Pull request by afck**
This temporarily replaces `Service::connect` with a TCP-only version, since there are still unsolved UTP issues.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/541)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/541)*

**Comment by Viv-Rajkumar** [comment]
Merging this to allow the testing of the tcp version of the system to continue.

**Pull request merged**
