### PR TITLE
Fix reporter and make sure it compiles when tests are run

### PR DESCRIPTION
**Pull request by madadam**
~~Do not merge yet!~~ Should be OK to merge now.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/566)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Is it ready for review?

**Comment by madadam** [comment]
Yes.

**Comment by vinipsmaker** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/566)*

**Pull request merged**
