### PR TITLE
feat/active_connections: Send data_len first then data

### PR DESCRIPTION
**Pull request by maqi**
Sending data_len first then data.
On receiving side, read size first, then reading data

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/690)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/connection_states/active_connection.rs, line 102 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/690#-KHu_6Hk85W_ZZUwozgl:-KHu_6Hk85W_ZZUwozgm:-320745628) ([raw file](https://github.com/maidsafe/crust/blob/1943a6e8b405f25bccb01d8619224c8f6cf8e37a/src/connection_states/active_connection.rs#L102)):*
> ```Rust
>     fn read_data(&mut self) {
>         if self.read_len == 0 && self.read_buf.len() >= U32_BYTE_LENGTH {
>             if let Ok(size) = Cursor::new(&self.read_buf[..]).read_u32::<LittleEndian>() {
> ```

Is it not safer to write this as `Cursor::new(&self.read_buf[..U32_BYTE_LENGTH]).read_u32::<LittleEndian>()`? Or is read_u32 immune to such errors ? Also if this fails, it's probably worth informing routing and closing connection because again the internal state of tracking the payload size and payload will be (probably) irrecoverably damaged. So maybe do a `.expect(...)` instead of `if let Ok(...)` here and put a TODO saying inform this to routing and gracefully terminate connection in actual production code

---

*[src/connection_states/active_connection.rs, line 112 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/690#-KHua7e_ctYUzPbZJ4bM:-KHua7e_ctYUzPbZJ4bN:1189455344) ([raw file](https://github.com/maidsafe/crust/blob/1943a6e8b405f25bccb01d8619224c8f6cf8e37a/src/connection_states/active_connection.rs#L112)):*
> ```Rust
>             self.read_buf = tail;
>             self.read_len = 0;
>             self.read_data();
> ```

Recursion may potentially leave an attack vector open - it's actually very easy to simulate - the sender can send great many number of small messages, say 20 MB of total data with each message as 20 bytes. This will cause huge number of recursions and it will be easier to get the receiver node panic with `Stack-Overflow`. Do you think a loop is much better here than recursion ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/690)*

**Comment by maqi** [comment]
*[src/connection_states/active_connection.rs, line 102 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/690#-KHu_6Hk85W_ZZUwozgl:-KHw8rzOm0wgVcxFQNUp:806214532) ([raw file](https://github.com/maidsafe/crust/blob/1943a6e8b405f25bccb01d8619224c8f6cf8e37a/src/connection_states/active_connection.rs#L102)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Is it not safer to write this as `Cursor::new(&self.read_buf[..U32_BYTE_LENGTH]).read_u32::<LittleEndian>()`? Or is read_u32 immune to such errors ? Also if this fails, it's probably worth informing routing and closing connection because again the internal state of tracking the payload size and payload will be (probably) irrecoverably damaged. So maybe do a `.expect(...)` instead of `if let Ok(...)` here and put a TODO saying inform this to routing and gracefully terminate connection in actual production code</details>
the simple_demo already shows `read_u32` can parse u32 from large vec.
However, I put in `[..U32_BYTE_LENGTH]` anyway.

I have put in `expect` and `TODO` comment as you mentioned. However, don't think it will happen, as `u32` use all 4 bytes 0x00 - 0xFF , so as long as their is 4 bytes, there will have a u32.

if the read size is incorrect, if less than real, then it will early return. if larger than real, it will hang. 
I think introducing time_out to prevent such hang shall be considered but be in a different PR? so I put a `TODO` commnet as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/690)*

**Comment by ustulation** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/690)*

**Pull request merged**
