### PR TITLE
fixes using unstable set_broadcast method

### PR DESCRIPTION
**Pull request by mmoadeli**
fixes issue #223 

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/224)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by rossmuir** [comment]
Is this really the only fix? As this does not move us closer to transitioning to beta / stable?

**Comment by mmoadeli** [comment]
@rossmuir : this is the fix, as long as we want to use unstable features. Using unstable features is not allowed in stable rust.

**Comment by rossmuir** [comment]
@mmoadeli I get this :smile:  but can we not find stable alternatives? > https://github.com/rust-lang/rust/commit/798ce502845435d94856a7b5fed5f703b06506d1 to a novice like me using `#[allow(deprecated)]` feels like just kicking the can down the road?

**Comment by mmoadeli** [comment]
@rossmuir I did not find the stable version of the function. My attempt was to let it compile. I will look for the proper fix, if I am asked so.

**Comment by Viv-Rajkumar** [comment]
@mmoadeli think @rossmuir has a valid point. Lets definitely look for stable alternatives as indicated in the linked commit and update where we can please. Gonna merge this to not have other libraries fail builds for now. can we have this raised as an issue please @rossmuir and assigned to @mmoadeli

**Pull request merged**
