### PR TITLE
Don't do rendezvous connects, if we have public IP

### PR DESCRIPTION
**Pull request by povilasb**
Addresses https://github.com/maidsafe/crust/issues/889
Basically, if there's a listener who successfully uses `bind_public()` from `p2p`, then `Crust` can be contacted directly and rendezvous connections should be avoided.

There's still one TODO though:
> // TODO(povilas): remove public address when listener gets dropped

but I figured this can be done with future PR.

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @canndrew (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by povilasb** [comment]
Also, note that how `Acceptor` is just a thin wrapper around `Listeners`: https://github.com/maidsafe/crust/pull/919/commits/5c10d642b1867dc1b448a84d48798845f5415cde#diff-5ed291e9fb97fc09364e19d6d2311f42R61

I'd like to remove `Acceptor` completely and rename `Listeners` to `Acceptor` instead. Then we'd have `Acceptor` and `Listener` structs instead of  `Acceptor`, `Listeners` and `Listener`.
@canndrew what do you think?

**Comment by canndrew** [comment]
> I'd like to remove `Acceptor` completely and rename `Listeners` to `Acceptor` instead.

I guess that makes sense. There's quite a lot of indirection in there at the moment.

**Comment by ustulation** [comment]
OS X hung, rest of CIs pass.

**Pull request merged**
