### PR TITLE
Benchmark

### LINKED ISSUE #424: Benchmark application
This issue was created just to separate discussion of the code from what the benchmark should measure.

A list to take into consideration:

- In the short-term, we should measure message throughput. This should be the focus now. We can benchmark numbers of nodes and network stability later.
- It should be nice if we can customize messages count and messages size, so we can tune values to adjust the test to the routing needs and common use case.
- We can take inspiration on [mio benchmark](https://github.com/carllerche/mio/blob/master/test/benchmark.rs).

### PR DESCRIPTION
**Pull request by vinipsmaker**
Fixes #424

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/425)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
```
vinipsmaker ~/Projetos/maidsafe/crust $ cargo run --example simple_benchmark -- -s 1048576 -n 5
     Running `target/debug/examples/simple_benchmark -s 1048576 -n 5`
Throughput: 303092.13470483245 bytes/second
```

My CPU setup:

```
vinipsmaker ~/Projetos/maidsafe/crust $ cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i7 CPU       L 640  @ 2.13GHz
stepping        : 5
microcode       : 0x4
cpu MHz         : 1599.000
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm ida arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs            :
bogomips        : 4257.43
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i7 CPU       L 640  @ 2.13GHz
stepping        : 5
microcode       : 0x4
cpu MHz         : 1466.000
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 2
cpu cores       : 2
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm ida arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs            :
bogomips        : 4257.43
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by vinipsmaker** [comment]
The Windows failure is unrelated to our code and is already being worked on: https://github.com/seanmonstar/num_cpus/issues/15

Let's wait for the fix and retrigger the CI build.

**Comment by vinipsmaker** [comment]
CI test is passing. PR can be merged now.

**Pull request merged**
