### PR TITLE
Add OurContactInfo::make_their_info method

### PR DESCRIPTION
**Pull request by canndrew**
Routing will need this.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/489)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
`OurContactInfo::make_their_info` isn't used nor part of the public API. Won't the compiler complain about unused method?

**Comment by canndrew** [comment]
It should be part of the public.API :/. The compiler didn't complain.

**Comment by vinipsmaker** [comment]
> It should be part of the public.API :/.

[My bad](http://www.urbandictionary.com/define.php?term=My+bad&defid=796865).

**Pull request merged**
