### PR TITLE
Enter REPL without needing to bootstrap first.

### PR DESCRIPTION
**Pull request by canndrew**
Fix for bug #327. With this, only the `running_speed_test` executing branch will block waiting for a bootstrap connection.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/351)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @inetic (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by vinipsmaker** [comment]
Please re-enable `unsafe_code` lint

**Comment by canndrew** [comment]
That would mean forgoing the use of `select!`. I think we need to decide on a general policy regarding whether we want to allow `select!` or not. It's pretty much a necessity in code that uses lots of channels.

**Comment by Fraser999** [comment]
Our current policy is to try and get off the Nightly channel, so effectively this precludes the use of `select!`.  I haven't any direct experience of using it, but if it's as helpful as you're indicating, should we be looking at implementing our own copy until the official one is stabilised?

Also, we're using a standard set of lint settings across all of our projects now, and I think any changes to these should be discussed before being made.  They were added in a rush, so I expect some or all could be debated, but it would be good as a company to get into a habit of not changing these without prior discussion and agreement.

**Comment by canndrew** [comment]
> but if it's as helpful as you're indicating, should we be looking at implementing our own copy until the official one is stabilised?

[Rust's tracking issue](https://github.com/rust-lang/rust/issues/27800) for stabilizing `select!` lists some third-party alternatives but I haven't looked into any of them.

> Also, we're using a standard set of lint settings across all of our projects now, and I think any changes to these should be discussed before being made. They were added in a rush, so I expect some or all could be debated, but it would be good as a company to get into a habit of not changing these without prior discussion and agreement.

Agreed.

**Pull request closed without merging**
