### PR TITLE
style/connection: several cleanups

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/675)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/675#-:-KHC71ne8ox4Ycq5tXDP:157696005)*

**Comment by dirvine** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/675)*

**Comment by dirvine** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/675)*

**Comment by dirvine** [comment]
Sorry @afck this needs rebase. Review all OK so no worries on merge when CI cycles again

**Pull request merged**
