### PR TITLE
improve uTP bootstrap connect

### LINKED ISSUE #587: Improve uTP connection logic
We should send the connection _syn_ to every address from the remote peer at once and only start waiting for a proper receive. Sending part should be done in parallel, so we don't risk receiving the message before we call the `recv_from` function (and thus losing the packet).

https://github.com/maidsafe/crust/blob/1d0392fc42ac95dce7c3c9af03e3744091aefb3c/src/connection.rs#L188

### PR DESCRIPTION
**Pull request by vinipsmaker**
Fixes #587

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/598)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
`"TcpNetworkReader"` seems like a copy-paste error and it might be a good idea to log any errors that come from `send_to` (although I know we weren't doing that before).

Other than that, this looks sensible though.

**Comment by vinipsmaker** [comment]
> `"TcpNetworkReader"` seems like a copy-paste error

Done.

> and it might be a good idea to log any errors that come from `send_to` (although I know we weren't doing that before).

Done.

**Comment by canndrew** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/598)*

**Comment by canndrew** [comment]
> This branch is out-of-date with the base branch

**Comment by vinipsmaker** [comment]
> This branch is out-of-date with the base branch

Rebased against master.

**Comment by Viv-Rajkumar** [comment]
merged this with #610

**Pull request closed without merging**
