### PR TITLE
ServiceDiscovery

### PR DESCRIPTION
**Pull request by ustulation**
Correcting more mistakes

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/700)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
*[src/service.rs, line 317 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRMwQwXBSRuuWnGzyN:-KIRMwQx84bDgIUdYhmg:1088204283) ([raw file](https://github.com/maidsafe/crust/blob/8260df6a60ff36b4fb86d0479760693b20e3dd70/src/service.rs#L317)):*
> ```Rust
> 
>     #[test]
>     fn bootstrap_connection_two_services() {
> ```

I don't think it is a good idea to remove the whole test.
we shall keep this to show how two service connected to each other step by step,
from the routing perspective, so this tests acts as a demo how curst service to be used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/service_discovery/mod.rs, line 46 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNUiFM6w9RPHc2sxu:-KIRNUiG1B2aYqw-sSxP:1839062476) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L46)):*
> ```Rust
> enum DiscoveryMsg {
>     Request {
>         guid: u64,
> ```

as we don't startup any separate threads anymore, shall the name guid be changed to something else? if it is really required.

---

*[src/service_discovery/mod.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNqQMBe1GeJ1T52pH:-KIRNqQMBe1GeJ1T52pI:953517948) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L118)):*
> ```Rust
> 
>     /// Register service discovery observer
>     pub fn _register_observer(&mut self, obs: Sender<StaticContactInfo>) {
> ```

who shall call this function, routing or other crust connection?

---

*[src/service_discovery/mod.rs, line 211 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRO5M37_vnmVjxBDEU:-KIRO5M4sp5p0N6no9Qm:1005339974) ([raw file](https://github.com/maidsafe/crust/blob/8260df6a60ff36b4fb86d0479760693b20e3dd70/src/service_discovery/mod.rs#L211)):*
> ```Rust
>             let _ = core.remove_state(&context);
>         }
>         let _ = self.routing_tx.send(Event::ServiceDiscoveryTerminated);
> ```

those observers not interested in whether the service_discovery is terminated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/service_discovery/mod.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNqQMBe1GeJ1T52pH:-KIRTrE2_eLdgKFWtyXd:101715034) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L118)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> who shall call this function, routing or other crust connection?
</details>
if we do think crust connection shall be the ones registering as observer, I think we shall use mio's messaging instead of mpsc::channel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by ustulation** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/service.rs, line 317 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRMwQwXBSRuuWnGzyN:-KIR_e2Xs8xkEqThu4Y6:-2134857333) ([raw file](https://github.com/maidsafe/crust/blob/8260df6a60ff36b4fb86d0479760693b20e3dd70/src/service.rs#L317)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> I don't think it is a good idea to remove the whole test.
> we shall keep this to show how two service connected to each other step by step,
> from the routing perspective, so this tests acts as a demo how curst service to be used.
</details>
This test is fake right now. The bootstrapping hasnt even been coded. All this test is doing is test service discovery and too from routing perspective when routing should not be concerned abt data received frm service discovery. This test should be added back and correctly once bootstrapping is atleast coded

---

*[src/service_discovery/mod.rs, line 46 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNUiFM6w9RPHc2sxu:-KIRbGIUDPK9r_rJNeYn:-1276741450) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L46)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> as we don't startup any separate threads anymore, shall the name guid be changed to something else? if it is really required.
</details>
Guid has nothing tobdo with threads. If we broadcast something to a port and if we happen to be bound to the same port we will receive our request back which we dont wany to respond to. Guid is important here.

---

*[src/service_discovery/mod.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNqQMBe1GeJ1T52pH:-KIRaptGS-z37mrnU7in:1520624708) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L118)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> if we do think crust connection shall be the ones registering as observer, I think we shall use mio's messaging instead of mpsc::channel
</details>
Crust. In previous code it is only called by bootstrap to collect info and that too just once.

---

*[src/service_discovery/mod.rs, line 211 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRO5M37_vnmVjxBDEU:-KIRacTXs0Vekw5nYxhZ:-36461285) ([raw file](https://github.com/maidsafe/crust/blob/8260df6a60ff36b4fb86d0479760693b20e3dd70/src/service_discovery/mod.rs#L211)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> those observers not interested in whether the service_discovery is terminated?
</details>
No not for now. Previous code didnt care, so i think we will code it later if required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
*[src/service_discovery/mod.rs, line 46 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNUiFM6w9RPHc2sxu:-KIRhAFEZr8Kmw-xq6xA:446125765) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L46)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Guid has nothing tobdo with threads. If we broadcast something to a port and if we happen to be bound to the same port we will receive our request back which we dont wany to respond to. Guid is important here.
</details>
i would prefer not to call it guid as it is kind of misleading. previous we use the word of guid mainly because there is a separate thread started up for that purpose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/service_discovery/mod.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/700#-KIRNqQMBe1GeJ1T52pH:-KIRhRy7XtOXFT8WGEDA:844682477) ([raw file](https://github.com/maidsafe/crust/blob/039bcdd67c446337bc91615fa432a1c6cff2d9a1/src/service_discovery/mod.rs#L118)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Crust. In previous code it is only called by bootstrap to collect info and that too just once.
</details>
ok, if it is only being called once during the startup process at the beginning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Comment by maqi** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/700)*

**Pull request merged**
