### PR TITLE
MAID-1161: Update start_listening() to take no parameters

### PR DESCRIPTION
**Pull request by mmoadeli**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/185)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ned14

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
Examples don't work. Please update them as well.

**Comment by chandraprakash** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/connection_manager.rs, line 99 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/185#-Ju74UKEpN93-A7Zsawa)** ([raw file](https://github.com/maidsafe/crust/blob/0538dab54e49fa8a0b1a165f80be0438b3e4aea8/src/connection_manager.rs#L99)):</sup>
Update to 
/// The actual `Port` used will be returned on which it started accepting for each protocol.

---

<sup>**[src/connection_manager.rs, line 804 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/185#-Ju78Ij2Ob8eKWyRSazr)** ([raw file](https://github.com/maidsafe/crust/blob/0538dab54e49fa8a0b1a165f80be0438b3e4aea8/src/connection_manager.rs#L804)):</sup>
No need this one as its already done during the construction of temp_configs

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/185)

**Comment by chandraprakash** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[examples/crust_peer.rs, line 281 \[r4\]](https://reviewable.io:443/reviews/maidsafe/crust/185#-Ju7A__XAX2V_8gVcy7d)** ([raw file](https://github.com/maidsafe/crust/blob/8e35911215197637e778604024ec27332885953d/examples/crust_peer.rs#L281)):</sup>
Use port 0 if not provided 

---

<sup>**[examples/crust_peer.rs, line 340 \[r4\]](https://reviewable.io:443/reviews/maidsafe/crust/185#-Ju7APC4uY8kwgaarstN)** ([raw file](https://github.com/maidsafe/crust/blob/0556145ce1f065dc5b9c6367912b562857ed6978/examples/crust_peer.rs#L340)):</sup>
Need to print information for the users.

---

<sup>**[examples/simple_receiver.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/maidsafe/crust/185#-Ju7B7x6f3kzBKQo-wws)** ([raw file](https://github.com/maidsafe/crust/blob/0556145ce1f065dc5b9c6367912b562857ed6978/examples/simple_receiver.rs#L86)):</sup>
Need to print information for the users.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/185)

**Comment by chandraprakash** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/185)

**Pull request merged**
