### PR TITLE
travis OSX

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/206)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
@rossmuir  can you please help with jenkins-ci-win64.

**Comment by rossmuir** [comment]
@chandraprakash the jenkins slave had an issue windows now successful

**Pull request merged**
