### PR TITLE
feat/priority: implement message prioritization

### PR DESCRIPTION
**Pull request by ustulation**
All messages to be sent out now need to specify priority. Crust will do it best to ensure the higher priority (0 being the highest) messages are sent before any lower priority ones even if lower priority were the ones to come into the queue first. Priority ranges between 0 (highest) and 255 (lowest).

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/754)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJovv6FD5RHLYRbNZnz:-686478470) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
> ```Rust
>             try!(data.write_u32::<LittleEndian>(len as u32));
> 
>             let entry = self.write_queue.entry(priority).or_insert(VecDeque::with_capacity(10));
> ```

This will create a `VecDeque` whether the entry exists or not. It's better to use `or_insert_with` and `VecDeque::new` or `|| VecDeque::with_capacity(10)`.

---

*[src/core/state.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJowZKOP9WEmHKzzFW_:-KJowZKPqjQx3YXdmBms:523867920) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/core/state.rs#L24)):*
> ```Rust
> use mio::{EventLoop, EventSet, Handler, Token};
> 
> /// Priority of a message to be sent by Crust. Priority 0 being the highest and very unlikely to be
> ```

It will probably make sense to actually _never_ drop priority 0 (that's what we currently do in master).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp-sYLDp_W2r_UZL9M:-440690615) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
> This will create a VecDeque whether the entry exists or not
But that is what i want - if the entry does not exist create a default one so that i can do a push back in the next line below. Sorry i didn't get this point could you explain more ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp0N5w1Uw7B1k6Dh7D:-1299724977) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
> This will create a VecDeque whether the entry exists or not

But that is what i want - if the entry does not exist create a default one so that i can do a push back in the next line below. Sorry i didn't get this point could you explain more ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by afck** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp0UibJHztG-UUmEps:55218022) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> > This will create a VecDeque whether the entry exists or not
> 
> But that is what i want - if the entry does not exist create a default one so that i can do a push back in the next line below. Sorry i didn't get this point could you explain more ?
> 
</details>
If the entry doesn't exist it's fine. But if it _does_ exist, this will allocate a new `VecDeque` anyway and pass it ot the `or_insert` method, just to have it dropped there again.
`or_insert_with(VecDeque::new)` would only call the `VecDeque::new` constructor if it actually needs it, i. e. if the entry actually doesn't exist, avoiding the unnecessary allocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp19FSL2M74rHmsutQ:-166095123) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> If the entry doesn't exist it's fine. But if it _does_ exist, this will allocate a new `VecDeque` anyway and pass it ot the `or_insert` method, just to have it dropped there again.
> `or_insert_with(VecDeque::new)` would only call the `VecDeque::new` constructor if it actually needs it, i. e. if the entry actually doesn't exist, avoiding the unnecessary allocation.
</details>
I dont think that is how it works (either that or my head isnt't functioning correctly)
https://doc.rust-lang.org/nightly/std/collections/btree_map/enum.Entry.html#method.or_insert
So from that - if the entry does not exist it will use the default, if it does then it will return the existing. That is what _default_ means i hope in that function parameter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by afck** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp252m2go3zOUePkaG:505225277) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> I dont think that is how it works (either that or my head isnt't functioning correctly)
> https://doc.rust-lang.org/nightly/std/collections/btree_map/enum.Entry.html#method.or_insert
> So from that - if the entry does not exist it will use the default, if it does then it will return the existing. That is what _default_ means i hope in that function parameter
</details>
That's what the `or_insert` method does, yes. However, it is _called_ in either case, and as an argument it takes the newly (and often unnecessarily) allocated `VecDeque`. It then either inserts it or drops it, which is a waste.
The `or_insert_with` method takes an `FnOnce` instead and only calls that if the entry is empty. If that `FnOnce` is where the new `VecDeque` is being allocated, the allocation actually is avoided if the entry is empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by ustulation** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJovv6EByeZw0rKGDZU:-KJp5UCn1r6DXOOUfnaR:2125488977) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/socket.rs#L150)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> That's what the `or_insert` method does, yes. However, it is _called_ in either case, and as an argument it takes the newly (and often unnecessarily) allocated `VecDeque`. It then either inserts it or drops it, which is a waste.
> The `or_insert_with` method takes an `FnOnce` instead and only calls that if the entry is empty. If that `FnOnce` is where the new `VecDeque` is being allocated, the allocation actually is avoided if the entry is empty.
</details>
Ah right i see what you mean - i've used a lamda instead now

---

*[src/core/state.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/754#-KJowZKOP9WEmHKzzFW_:-KJp0jyMa-yOA8gXC1OW:677588487) ([raw file](https://github.com/maidsafe/crust/blob/980e47d98f6c7bee2d77d0bba4aa023761873696/src/core/state.rs#L24)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> It will probably make sense to actually _never_ drop priority 0 (that's what we currently do in master).
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Comment by afck** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/754)*

**Pull request merged**
