### PR TITLE
Vinipsmaker test utp

### PR DESCRIPTION
**Pull request by vinipsmaker**
CIs will fail to build until we release the new version of rust-utp.

However, tests are running fine on my local machine.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/451)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Only bother to take a look into this PR once https://github.com/maidsafe/rust-utp/pull/9 is merged and a new version of `temp_utp` is released.

**Comment by vinipsmaker** [comment]
Continued work from https://github.com/maidsafe/crust/pull/442

**Comment by vinipsmaker** [comment]
Gonna close this PR, as I rewrote history (`git rebase -i`) to have much cleaner PR on #454.

**Pull request closed without merging**
