### PR TITLE
Rust UTP wip - DO NOT MERGE

### PR DESCRIPTION
**Pull request by ned14**
Pull request purely for people to watch the Rust UTP port progress

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/163)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @chandraprakash

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ned14** [comment]
utp_connections::test_small_stream unit test is now finally passing and is stable. Yay!

**Comment by dirvine** [comment]
Excellent news Niall - have a beer :-)

On Thu, Jun 25, 2015 at 6:23 PM, Niall Douglas <notifications@github.com>
wrote:

> utp_connections::test_small_stream unit test is now finally passing and is
> stable. Yay!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maidsafe/crust/pull/163#issuecomment-115332497>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by chandraprakash** [comment]
Nice one Niall !!!

**Pull request closed without merging**
