### PR TITLE
Get rid of get_if_addrs

### PR DESCRIPTION
**Pull request by canndrew**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/767)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Cargo.toml, line 27 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/767#-KKTDdWoweL_HYxMzR9G:-KKTDdWoweL_HYxMzR9H:2066263401) ([raw file](https://github.com/maidsafe/crust/blob/fd743d87c42f0370947d5cd12279c625c2079442/Cargo.toml#L27)):*
> ```TOML
> tmp_mio = "~0.5.2"
> c_linked_list = "~1.1.0"
> libc = "0.2"
> ```

does not follow conventiion of `~major.minor.patch`. Pls also use `cargo add libc` that will rearrange everything alphabetically

---

*[src/nat/mapping_context.rs, line 25 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/767#-KKTDxOlMIdigdxXapeG:-KKTDxOm_DsE_1_SNM_u:2029534337) ([raw file](https://github.com/maidsafe/crust/blob/fd743d87c42f0370947d5cd12279c625c2079442/src/nat/mapping_context.rs#L25)):*
> ```Rust
> use crossbeam;
> use igd::{self, Gateway};
> use common::get_if_addrs::{self, IfAddr};
> ```

Alphabetically pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/767)*

**Comment by ustulation** [comment]
Please re-base and incorporate review comments.

**Comment by canndrew** [comment]
> Please re-base and incorporate review comments.
Done. Why was this closed though?

**Pull request closed without merging**
