### PR TITLE
Replace println with logging.

### PR DESCRIPTION
**Pull request by s-brian**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/250)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
It seems okay to me. Can I merge it? ( @chandraprakash ? )

**Comment by chandraprakash** [comment]
@vinipsmaker Yes :-)

**Pull request merged**
