### PR TITLE
Remove socket_addr crate

### PR DESCRIPTION
**Pull request by canndrew**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/766)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 1 of 14 files at r1.
Review status: 1 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/common/message.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO854USROoAABd775T:-KKO854USROoAABd775U:-26099783) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/common/message.rs#L19)):*
> ```Rust
> 
> use sodiumoxide::crypto::box_::PublicKey;
> use common::{NameHash, socket_addr};
> ```

let have this arranged alphabetically

---

*[src/common/mod.rs, line 37 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO8G8FJey1Kr14-7oz:-KKO8G8GmxPAM3nJtdTc:-534341075) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/common/mod.rs#L37)):*
> ```Rust
> mod socket;
> mod state;
> pub mod socket_addr;
> ```

make it a private module and expose via `pub use` as the rest above - pls follow the same pattern

---

*[src/main/bootstrap/mod.rs, line 37 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO8YbXkVa19sFXjr47:-KKO8YbXkVa19sFXjr48:187990113) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/main/bootstrap/mod.rs#L37)):*
> ```Rust
> use service_discovery::ServiceDiscovery;
> use sodiumoxide::crypto::box_::PublicKey;
> use common::socket_addr;
> ```

alphabetically pls

---

*[src/main/connection_listener/exchange_msg.rs, line 27 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO8afKMqu7c7WgjRnM:-KKO8afKMqu7c7WgjRnN:187990113) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/main/connection_listener/exchange_msg.rs#L27)):*
> ```Rust
> use mio::{EventLoop, EventSet, PollOpt, Timeout, Token};
> use sodiumoxide::crypto::box_::PublicKey;
> use common::socket_addr;
> ```

alphabetically pls

---

*[src/main/connection_listener/mod.rs, line 199 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO8bZrpdVYFfuHCHWq:-KKO8bZrpdVYFfuHCHWr:187990113) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/main/connection_listener/mod.rs#L199)):*
> ```Rust
>     use maidsafe_utilities::thread::RaiiThreadJoiner;
>     use nat::MappingContext;
>     use common::socket_addr::SocketAddr;
> ```

alphabetically pls

---

*[src/tests/mod.rs, line 29 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKO8ggB2hx27Hx80NPG:-KKO8ggB2hx27Hx80NPH:187990113) ([raw file](https://github.com/maidsafe/crust/blob/0447055f0f9389beb23f92a249c5e87be8ffda1f/src/tests/mod.rs#L29)):*
> ```Rust
> use main::{Config, Event, Service};
> use common::socket_addr::SocketAddr;
> ```

alphabetically pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/766)*

**Comment by ustulation** [comment]
Review status: 1 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/common/mod.rs, line 24 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKSt3a0n9Oq2SJgQmc-:-KKSt3a0n9Oq2SJgQmc0:-1269584150) ([raw file](https://github.com/maidsafe/crust/blob/5026c66ffe2a36b3ade6af8ba55047d61c35e0ce/src/common/mod.rs#L24)):*
> ```Rust
> pub use self::socket::Socket;
> pub use self::state::State;
> pub use self::socket_addr::SocketAddr;
> ```

not alphabetical

---

*[src/common/socket_addr.rs, line 6 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKSt9elV3YQeG2sOkOP:-KKSt9elV3YQeG2sOkOQ:-248363891) ([raw file](https://github.com/maidsafe/crust/blob/5026c66ffe2a36b3ade6af8ba55047d61c35e0ce/src/common/socket_addr.rs#L6)):*
> ```Rust
> use std::str::FromStr;
> 
> use rustc_serialize::{Encodable, Encoder, Decodable, Decoder};
> ```

not alphabetical - these can be automate by rustfmt - add `reorder_imports = true` in `rustfmt.toml` and keep it in some parent dir so that it applies to all your maidsafe code in crates we work with

---

*[src/main/connection_listener/exchange_msg.rs, line 25 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/766#-KKSto1lnRJI9kWOmUbR:-KKSto1lnRJI9kWOmUbS:1523276016) ([raw file](https://github.com/maidsafe/crust/blob/5026c66ffe2a36b3ade6af8ba55047d61c35e0ce/src/main/connection_listener/exchange_msg.rs#L25)):*
> ```Rust
> use main::{ActiveConnection, ConnectionCandidate, ConnectionId, ConnectionMap, Event, PeerId};
> use main::peer_id;
> use common::{self, Context, Core, Message, NameHash, Priority, Socket, State};
> ```

alphabetical pls (`common` before `main`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/766)*

**Comment by ustulation** [comment]
Reviewed 1 of 14 files at r1, 8 of 11 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/766)*

**Pull request merged**
