### PR TITLE
feat/timestamp_priority: timestamping queuing msgs

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/756)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/socket.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtpOViEa067Dl5zseH:-KJtpOViEa067Dl5zseI:594749127) ([raw file](https://github.com/maidsafe/crust/blob/9515b2ca714dbf065fce8c5412ee37109e2be6f8/src/socket.rs#L24)):*
> ```Rust
> use std::time::Instant;
> 
> use byteorder::{LittleEndian, ReadBytesExt, WriteBytesExt};
> ```

Are these imports actually needed? They seem to have nothing to do with the timestamps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtpOViEa067Dl5zseH:-KJttqUKVTzTSp9KOavf:-312582030) ([raw file](https://github.com/maidsafe/crust/blob/9515b2ca714dbf065fce8c5412ee37109e2be6f8/src/socket.rs#L24)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Are these imports actually needed? They seem to have nothing to do with the timestamps.
</details>
think these are just due to reordering - they were somewhere below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtpOViEa067Dl5zseH:-KJttgriYtySdZnjX-n7:-638611459) ([raw file](https://github.com/maidsafe/crust/blob/9515b2ca714dbf065fce8c5412ee37109e2be6f8/src/socket.rs#L24)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Are these imports actually needed? They seem to have nothing to do with the timestamps.
</details>
they are just being re-arranged in an alphabet order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/socket.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtpOViEa067Dl5zseH:-KJtuUGV4ikuDf3Da5At:-1890254988) ([raw file](https://github.com/maidsafe/crust/blob/9515b2ca714dbf065fce8c5412ee37109e2be6f8/src/socket.rs#L24)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> they are just being re-arranged in an alphabet order
</details>
Ah, right, sorry!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJtyalbFcmauyZNcwc6:-348534350) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
> ```Rust
>                                queue.len(),
>                                priority);
>                         queue.clear();
> ```

if clearing the queue, do make sure it plays well with the logic below that expect and queue to be non empty if it is in the hashmap - so either that or this might require a change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by afck** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJtzggHo8JA7m8TJGzw:-827293503) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> if clearing the queue, do make sure it plays well with the logic below that expect and queue to be non empty if it is in the hashmap - so either that or this might require a change
</details>
Good point, I totally missed that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJu3O3OZpurNuG-VgPR:231853304) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Good point, I totally missed that!
</details>
changed to remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJu7VGkLSqubxJ9e5AR:1426490321) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> the condition doesnt seem right - it's going to delete all messages that dont have priority as 0. Maybe you want an AND instead of OR and `>` instead of `<=`
</details>
resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJu8fSXtOgginGDUZ7I:173763253) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> resolved.
</details>
Unlike crust master, this is now only going to remove the queues with an expired entry, but not _all the following_ queues, too. I guess that's fine, too, though.

But: it still doesn't work with the `expect` below, does it? Now the queue might be completely empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJuA9dMti8zcKTT6qMj:610868974) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Unlike crust master, this is now only going to remove the queues with an expired entry, but not _all the following_ queues, too. I guess that's fine, too, though.
> 
> But: it still doesn't work with the `expect` below, does it? Now the queue might be completely empty.
</details>
the whole entry will be removed, which means you won't get a `queue` at all.
when `queue` carried `pop_front()`, an empty check will be carried out immediately after that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJuB-eeDuVNuG2_k0jY:-489252192) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> the whole entry will be removed, which means you won't get a `queue` at all.
> when `queue` carried `pop_front()`, an empty check will be carried out immediately after that.
</details>
regarding `remove all non 0 priority entries, whenever one of it having expired front`,  we are now using `hashmap` which means the entries are no longer ordered in sequence, is it the case? if so, I think some corrections need to be applied (instead of using `next` directly, i.e. it's supposed to sending by priority, and 0 is highest, right?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJuBw-WR8lApVIZAmIM:-1525979299) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> regarding `remove all non 0 priority entries, whenever one of it having expired front`,  we are now using `hashmap` which means the entries are no longer ordered in sequence, is it the case? if so, I think some corrections need to be applied (instead of using `next` directly, i.e. it's supposed to sending by priority, and 0 is highest, right?)
</details>
Ah, I see! Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by ustulation** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJuRUh7tRbhpr6SWAqM:1126791287) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Ah, I see! Thanks!
</details>
should be `map_or(true` instead of `false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Comment by maqi** [comment]
*[src/socket.rs, line 151 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/756#-KJtyalbFcmauyZNcwc5:-KJuUFY0Ok7J_lLiX1LP:1847131133) ([raw file](https://github.com/maidsafe/crust/blob/b240fdac1d754814cc8e00c67d6600d4b1a223ad/src/socket.rs#L151)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> should be `map_or(true` instead of `false`.
</details>
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/756)*

**Pull request merged**
