### PR TITLE
IGD support

### PR DESCRIPTION
**Pull request by vinipsmaker**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/715)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/igd/http_request.rs, line 94 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjTZNaBvcKyJ2MZb9D:-KJjTZNaBvcKyJ2MZb9E:-201817896) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L94)):*
> ```Rust
>              token: Token,
>              event_set: EventSet) {
>         if !event_set.is_readable()
> ```

Is it not better as `if error() || hup() { .. } else { if readable() {...} if writable() {...} }`

---

*[src/igd/http_request.rs, line 125 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjTw9b1CWeo7O9kJUI:-KJjTw9b1CWeo7O9kJUJ:264690635) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L125)):*
> ```Rust
>                     let read = match self.socket.read(&mut buf) {
>                         Ok(r) => r,
>                         Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => break,
> ```

Maybe also include `ErrorKind::Interrupted` which is benign as well and not and error

---

*[src/igd/http_request.rs, line 150 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjU84e1sHVzKUtHtNG:-KJjU84fItkiBpS30KfS:476199769) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L150)):*
> ```Rust
>                             Ok(None) => break,
>                             Err(e) => {
>                                 self.callback.invoke(Err(HttpError::ParsingError(e)),
> ```

why are we not dergistering token from mio loop followed by removing context and token from `core` ?  Do you still want them there ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/715)*

**Comment by vinipsmaker** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/igd/http_request.rs, line 94 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjTZNaBvcKyJ2MZb9D:-KJjkZ57p8Nj1X6mGipk:-1751043909) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L94)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Is it not better as `if error() || hup() { .. } else { if readable() {...} if writable() {...} }`
</details>
HTTP/1.0 closes the connection after the response is sent. I want to avoid discarding any data. There **will** be a hup/error after the reply is sent, but there will also be buffered data to be read.

---

*[src/igd/http_request.rs, line 150 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjU84e1sHVzKUtHtNG:-KJjmMIL73XnwBu1cSBH:915860270) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L150)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> why are we not dergistering token from mio loop followed by removing context and token from `core` ?  Do you still want them there ?
</details>
That's why I wanted your review for. Gonna fix these errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/715)*

**Comment by vinipsmaker** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/igd/http_request.rs, line 125 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjTw9b1CWeo7O9kJUI:-KJk-iSGEAUuZp7NTKb3:-499146009) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L125)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Maybe also include `ErrorKind::Interrupted` which is benign as well and not and error
</details>
Done.

---

*[src/igd/http_request.rs, line 150 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/715#-KJjU84e1sHVzKUtHtNG:-KJk-kxV9DBLRSSx1l6W:-499146009) ([raw file](https://github.com/maidsafe/crust/blob/b1d68a33a984b1b19d9f95fdd38ef4f7be1e0760/src/igd/http_request.rs#L150)):*
<details><summary><i>Previously, vinipsmaker (Vinícius dos Santos Oliveira) wrote…</i></summary>
> That's why I wanted your review for. Gonna fix these errors.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/715)*

**Comment by ustulation** [comment]
This is no longer needed right now. Existing IGD has been intrgrated and crust is working fine with it.

**Pull request closed without merging**
