### PR TITLE
Move ConnectionInfo into the service module.

### PR DESCRIPTION
**Pull request by afck**
Once Rust has the pub(restricted) feature we can move these into their own module again: https://github.com/rust-lang/rfcs/pull/1422

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/515)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
+1 on this commit, it makes code simpler so therefore better

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/maidsafe/crust/515#-K9t4LnGtFj6Mf8FIpdf:-K9t4LnGtFj6Mf8FIpdg:157696005) (no related file):*
r? @dirvine

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/515)*

**Comment by dirvine** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/515)*

**Pull request merged**
