### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by vinipsmaker**
Increasing the use of monadic combinators to improve readability.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/133)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @ned14 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by Fraser999** [comment]
Hi Vinícius,

Good stuff indeed - thanks very much for this! It's a pretty big payback :-)

All the best,
Fraser.

**Comment by ned14** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- src/beacon.rs @ r1
- src/bootstrap_handler.rs @ r2
- src/connection_manager.rs @ r1
- src/getifaddrs.rs @ r1
- src/tcp_connections.rs @ r2
- src/transport.rs @ r1

---

<sup>**[src/bootstrap_handler.rs, line 56 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/133#-JrbiyKbjd5LCDet_5-f)** ([raw file](https://github.com/maidsafe/crust/blob/6159fdf9e5457b5ce607ae3be9e9ce225e0931d0/src/bootstrap_handler.rs#L56)):</sup>
How is this returning None if the String::from_utf8 fails?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/133)

**Comment by vinipsmaker** [comment]
> Just compiled without .iter() without problems. Release notes about this change can be found here:
>
> - https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-100-alpha2-february-2015

Thanks for the link, @oblitum. I wasn't aware of all behaviours. I'm aware now, but the code still looks fine (`contacts` is taken by copy, so no hidden side-effects).

**Comment by vinipsmaker** [comment]
Sorry for the possible mail spams you guys got because of me, but these highly spread notifications from GitHub tricked me to make comments on the wrong places about the wrong concerns.

**Comment by vinipsmaker** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/bootstrap_handler.rs, line 56 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/133#-JrbiyKbjd5LCDet_5-f)** ([raw file](https://github.com/maidsafe/crust/blob/6159fdf9e5457b5ce607ae3be9e9ce225e0931d0/src/bootstrap_handler.rs#L56)):</sup>
The `ok()` member-function converts an `Result<T, E>` to an `Option<T>`. This is exactly what the outer `match` from the previous code was doing.

Then we have the `Ok` case (look the previous code), where it's still possible to return `None`. If we only had the `Some` possibility within the `Ok` case (look the previous code), we could have use `map` and let the `map` function wrap the return from our closure into some `Some`. The `and_then` function looks like `map`, but you return an `Option`.

The inner `match` in the previous code where just converting the return from `json::decode(&contacts_str)` from `Result` to `Option`, which exactly what the member-function `ok` does for us. To be fair, the inner `match` was using control flow constructs to immediately return from `parse_contacts`, but we got the exactly same behaviour w/o these  `return`s, given Rust is an "expression-oriented" language.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/133)

**Comment by dirvine** [comment]
@vinipsmaker  You kidding, it's great to have the effort you have made here. thanks very much, it's not spam :-)

**Comment by dirvine** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/getifaddrs.rs, line 91 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/133#-Jrc7vzVXcw4lrD6uf4k)** ([raw file](https://github.com/maidsafe/crust/blob/6159fdf9e5457b5ce607ae3be9e9ce225e0931d0/src/getifaddrs.rs#L91)):</sup>
Nice

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/133)

**Comment by ned14** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/bootstrap_handler.rs, line 56 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/133#-JrbiyKbjd5LCDet_5-f)** ([raw file](https://github.com/maidsafe/crust/blob/6159fdf9e5457b5ce607ae3be9e9ce225e0931d0/src/bootstrap_handler.rs#L56)):</sup>
Yep, you're right. I forgot Result.ok() yields an Option. Sorry.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/133)

**Pull request merged**
