### PR TITLE
chore/crust: Refactor to use mio

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/680)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
*[src/service.rs, line 137 \[r2\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZmGaFJAD3hP4YgdBA:-KHZmGaGamCknfZGoxLZ:1949733394) ([raw file](https://github.com/maidsafe/crust/blob/53305e46c2792d3e304bacd7efb3ce384be7ec8d/src/service.rs#L137)):*
> ```Rust
>         let mapping_context = self.mapping_context.clone();
>         let our_pub_key = self.our_keys.0.clone();
>         let _ = self.sender.send(Box::new(move |_: &mut EventLoop<Core>, _: &mut Core| {
> ```

If this is an error should we inform that too via `event_tx.send(ConnectionInfo(err))` or something similar to routing ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
Reviewed 4 of 7 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KHZs50J76H3I9_AVTp-:424850960) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
> ```Rust
>         })) {
>             let _ = self.event_tx.send(Event::MioNotificationError);
>         }
> ```

Ah no - this will be useless to routing - it does not know the context - you will have to create `Event::ConnectionInfoPrepare(ConnectionInfoResult { result: Err` etc .. Another thing to notice is that this error is not io::Result's error. So might be worthwhile extending it to CrustError enum and wrapping all `io::Result, MioResult` etc into it like other crates have successfully done so far. Then all results would be `Result<blahblah, CrustError>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by maqi** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KHZv4EybHNDioN2F2lp:-1726157972) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Ah no - this will be useless to routing - it does not know the context - you will have to create `Event::ConnectionInfoPrepare(ConnectionInfoResult { result: Err` etc .. Another thing to notice is that this error is not io::Result's error. So might be worthwhile extending it to CrustError enum and wrapping all `io::Result, MioResult` etc into it like other crates have successfully done so far. Then all results would be `Result<blahblah, CrustError>`</details>
I don't get it here. Such error only happens when the mio eventloop as a whole failed to accept the notification. So it's not a `ConnectionInfo` specific error.
Also, as such error returns immediately, I am even thinking it can be a return result of the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KH_-0UEHX4VPj8JkG-B:1109285593) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> I don't get it here. Such error only happens when the mio eventloop as a whole failed to accept the notification. So it's not a `ConnectionInfo` specific error.
> Also, as such error returns immediately, I am even thinking it can be a return result of the function.</details>
The context here is the token that routing passes - So you would be sending it as:
```
Event::ConnectionInfoPrepared(ConnectionInfoResult {
                result_token: result_token,
                result: Err(blahblah),
```
is much more useful to routing than saying - `Err(blah)` in some unknown context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KH_-wt3dKtAgjSVw6Mr:70033077) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> The context here is the token that routing passes - So you would be sending it as:
> ```
> Event::ConnectionInfoPrepared(ConnectionInfoResult {
>                 result_token: result_token,
>                 result: Err(blahblah),
> ```
> is much more useful to routing than saying - `Err(blah)` in some unknown context.</details>
Also i agree about immediate returns - that'll be more useful - but will change the API. Should we add that as TODO and return contextual error if that is a middle ground ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KH_0P8GnUi6LSS5CUEN:1765647690) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Also i agree about immediate returns - that'll be more useful - but will change the API. Should we add that as TODO and return contextual error if that is a middle ground ?</details>
Reviewable does not let me edit my comment - wanted to explain more - so here it is: Should we add that as TODO and  return contextual error like the way i showed above for just now, if that is an acceptable middle ground

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by maqi** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KH_1sZy0j1VjrwM7pXm:1019097060) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Reviewable does not let me edit my comment - wanted to explain more - so here it is: Should we add that as TODO and  return contextual error like the way i showed above for just now, if that is an acceptable middle ground</details>
I don't want to mess up with the API, so put a TODO to mention about the immediate return result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
*[src/service.rs, line 166 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/680#-KHZs50J76H3I9_AVToz:-KH_7b7mvgKe-e0uLGIT:-414055347) ([raw file](https://github.com/maidsafe/crust/blob/42981b4dc6e8a05feb21663fece12b1dfdfe3d0e/src/service.rs#L166)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> I don't want to mess up with the API, so put a TODO to mention about the immediate return result.</details>
cheers qi

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Comment by ustulation** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/680)*

**Pull request merged**
