### PR TITLE
Fixes dangling threads

### PR DESCRIPTION
**Pull request by madadam**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/466)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
This PR was created to address this issue: https://github.com/maidsafe/crust/issues/405#issuecomment-169263055

**Comment by vinipsmaker** [comment]
> Joining the UtpWrapper thread does not fix it though

You're joining the `UtpWrapper` thread, but there is more.

[When a connection is registered (the `UtpWrapper` object), the handle is added to the `State::connections` collection and two new threads are created](https://github.com/maidsafe/crust/blob/b4ec3f4109e8332d40dbd42b1e374c76a41df964/src/state.rs#L258). As all the communication is done using `mpsc::channel`, you just need to destroy one end of the channel to force the other end to also close (and the thread will eventually stop). You should update `Service::stop` to also take care of removing all connections.

**Comment by madadam** [comment]
Ok, I'll take a look at it. But even if we make sure we join all the threads that are spawned inside the service (and any objects used by it), it still won't solve the problem in #405. Because there are still multiple ways the connection can be broken without the `fin` packet being sent. For example:

- the peer process is killed forcefully (`kill - 9` ...)
- the peer machine is turned off, disconnected from power socket, physically destroyed, etc...
- the network goes down (router failure, power failure, cable being severed somewhere, etc...)
- and so on.

In none of this cases has the peer being disconnected chance to send the `fin` packet.

Anyway, even if this PR does not fix the problem in #405, I thinks it's still useful because I believe joining threads we spawn is something we should always be doing anyway.

**Comment by dirvine** [comment]
> I believe joining threads we spawn is something we should always be doing anyway.

To me we should use crossbeam::scope for this and similar things where we can. Just for future anyway

**Comment by madadam** [comment]
> To me we should use crossbeam::scope for this and similar things where we can. Just for future anyway

It seems that `crossbeam::scope` can only be used locally, inside a function. In this case we would need the crossbeam scope to be a member of a struct. We had a discussion on slack with @ustulation , @canndrew and @afck and the consensus was that crossbeam can't do that.

**Comment by dirvine** [comment]
Yws, if we want more than that there is a scoped threadpool (crates.io) as well which is not function local.  Carrying a joinguard across functions may appear an anti pattern in many ways.

**Comment by vinipsmaker** [comment]
> But even if we make sure we join all the threads that are spawned inside the service (and any objects used by it), it still won't solve the problem in #405.

Well, the problem was that we weren't sending the `fin` packet. It's okay to not receive a `fin` packet, as the connection will just time out and the other peer will drop the connection anyway (it just takes a little longer).

**Comment by madadam** [comment]
Ah, I see. So even if the service was terminated gracefully, it still wouldn't send the fin packet, correct? So I guess this PR then fixes it? If it does, let me just add an explicit test case for it and then you can merge it if you think it's ok.

**Comment by vinipsmaker** [comment]
> So I guess this PR then fixes it?

Not yet, do the changes I requested. The uTP thread might finish earlier/later. It's a race. If application exist, more likely it won't.

**Comment by madadam** [comment]
You mean joining the [reader / writer threads](https://github.com/maidsafe/crust/blob/b4ec3f4109e8332d40dbd42b1e374c76a41df964/src/state.rs#L295) associated with each connection in `State` when it is stopped/destroyed?

**Comment by vinipsmaker** [comment]
> You mean joining [...]

This would stall the application, you must close the associated channels (by dropping the connections) to request the threads to also exit.

**Comment by madadam** [comment]
Yeah, but the connections are dropped automatically when the `State` is dropped, aren't they? So it should be enough to make sure the threads are joined after the connections are dropped, shouldn't it?

**Comment by vinipsmaker** [comment]
> Yeah, but the connections are dropped automatically when the `State` is dropped, aren't they? So it should be enough to make sure the threads are joined after the connections are dropped, shouldn't it?

I'm seeing a deadlock. `State` joins the read/write threads. Connections aren't dropped (will be dropped later). `join` never returns, because threads don't finish, because connections weren't dropped.

It's possible to join the threads at other places anyway, so this can be avoided.

**Comment by madadam** [comment]
That's why I want to join the threads only *after* the connection are dropped. Yup, it shouldn't be too hard. Have to run now, but will push a fix tomorrow.

**Comment by madadam** [comment]
Fixed the dangling reader threads. Was caused by a `UtpWrapper` keeping a copy of output `Sender` which prevented the corresponding `Receiver` in the `UtpWrapper`'s thread to be closed.

**Comment by inetic** [comment]
Can we please wait with merging this one until we have the `test_network_utp` test in place? I have the test locally passing with [this PR](https://github.com/maidsafe/rust-utp/pull/13), but it also exposes the leaky thread problem. So I tried to apply this PR, but then the `test_network_utp` test started failing again.

**Comment by vinipsmaker** [comment]
> So I tried to apply this PR, but then the `test_network_utp` test started failing again.

I can investigate this issue. But I believe the problem is not this PR per si, but the crust side of things. Asio has a callback in the write operation, so you can choose to only really stop the service once TCP acknowledges proper delivery. The nodes from the test are like "when you receive a connection, send a message back and when you receive N messages, don't bother waiting for the pending messages to be delivered". Related to https://github.com/maidsafe/crust/issues/431 and how currently the "on-connect" event is delivered (versus the past version of it). This is just my suspicion, I need to properly investigate it.

> Can we please wait with merging this one until we have the `test_network_utp` test in place?

Sure we can wait, I can cherry-pick these commits and test locally to see if the new error is caused by this PR or by some other place.

In general, I think this PR is an improvement and there is nothing wrong with it. But waiting won't cause any trouble.

**Comment by vinipsmaker** [comment]
> This branch has conflicts that must be resolved

Please update your work, @madadam.

**Comment by madadam** [comment]
Fixed the merge conflicts.

**Comment by vinipsmaker** [comment]
Please undo [these style changes](https://github.com/madadam/crust/commit/49a621f0640943d2211a54aaa69800a451ebb154#diff-bfa17b8ec2b0aac77da5f96cbcbe4101R49) or @dirvine will make another commit that will force every PR to be rebased again.
😛

**Comment by vinipsmaker** [comment]
If you need help rewriting the commits, take a look into `git rebase -i`. It's a life-saver in these cases.

**Comment by madadam** [comment]
I'm just going to apply `rustfmt` to my changes.

**Comment by vinipsmaker** [comment]
> This branch has conflicts that must be resolved

**Comment by madadam** [comment]
Fixed the conflicts, but some tests are failing. There are also some `#[ignore]`'d tests which should be checked. I won't be able to maintain this PR anymore as I've been moved to another project. Good luck ;)

**Comment by vinipsmaker** [comment]
Gonna skip the following commits, as I believe they are just noise:

- https://github.com/madadam/crust/commit/8e5fd62508270510b06ed83b7c6b7e06b4eceaae
- https://github.com/madadam/crust/commit/417420b15f549d01f7a149a6efb8bb96092f7078

Also, continued your work on another PR, just to not having any conflicts with `master` at all while adding as little noise as possible: https://github.com/maidsafe/crust/pull/475

**Pull request closed without merging**
