### PR TITLE
Fix notification order

### PR DESCRIPTION
**Pull request by vinipsmaker**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/558)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
In `utp_rendezvous_connect` I don't like that we block while holding the lock on the connection map. Other than that though this looks good.

**Comment by vinipsmaker** [comment]
> In `utp_rendezvous_connect` I don't like that we block while holding the lock on the connection map. Other than that though this looks good.

It should be fixed now.

**Comment by canndrew** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/558)*

**Pull request merged**
