### PR TITLE
WIP: Single connection per peer in connection map

### PR DESCRIPTION
**Pull request by canndrew**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/676)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/crust/676)*

**Comment by afck** [comment]
Please don't merge this for now.
We tested this with routing (just starting 35 nodes) and are seeing lots of `LostPeer` events: Most nodes failed to join the network and those that did only got to routing table size 2.

**Comment by Viv-Rajkumar** [comment]
Closing this cos it's getting done for now with #683

**Pull request closed without merging**
