### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/498)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
This PR wasn't merged to `master`. Is this right?

**Comment by dirvine** [comment]
Yes it is a heavy refactor really so keeping out of master just now.

**Pull request merged**
