### PR TITLE
Use bootstrap cache

### PR DESCRIPTION
**Pull request by canndrew**
Clear static contact info from cache when a bootstrap connect fails.
Add new static contact info to cache on calls to Service::connect

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/572)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
This PR is broken. I'm working on some fixes to config_file_handler that will fix it.

**Comment by vinipsmaker** [comment]
> This PR is broken. I'm working on some fixes to config_file_handler that will fix it.

Let me know when it's ready.

**Comment by canndrew** [comment]
Hrm, dunno why that test hung on one of the appveyor runs.

**Comment by vinipsmaker** [comment]
Reviewed 1 of 5 files at r1, 2 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/config_handler.rs, line 39 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/572#-KCN6T6f0Wj_otTJLoR6:-KCN6T6gcaAX3tKqE1Mj:-124736793) ([raw file](https://github.com/maidsafe/crust/blob/c6f1ddad924079bd6bdd584fe22dec8065d85044/src/config_handler.rs#L39)):*
Cool. I didn't know about this trait.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/572)*

**Comment by vinipsmaker** [comment]
> This branch is out-of-date with the base branch

I'll open another PR and merge there based off this one.

**Comment by canndrew** [comment]
This is ready for review now @vinipsmaker

**Pull request closed without merging**
