### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/crust/154)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ned14

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
jenkins-ci-osx is not progressing from last 3 hours. 
@ned14  please merge this based on travis and jenkins results. 
I have notified @Fraser999 about  jenkins-ci-osx.

**Comment by chandraprakash** [comment]
I want this fixes merged before I do the version change PR :-)

**Pull request merged**
