### PR TITLE
More cleanup.

### PR DESCRIPTION
**Pull request by canndrew**
This is the sequel to https://github.com/maidsafe/crust/pull/620

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/crust/621)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
can you rebase against master?

**Comment by canndrew** [comment]
Rebased.

**Comment by vinipsmaker** [comment]
Reviewed 13 of 20 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/config_handler.rs, line 96 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY96wVOgXADgdMEQKL:-KDY96wW1XvI_y3DOkjF:-1458679648) ([raw file](https://github.com/maidsafe/crust/blob/6fb500f02e14b3b27d8c33a8b8a9c2e37e4e2aa4/src/config_handler.rs#L96)):*
next time just add `#[ignore]`. commenting/uncommenting code like this just make `git blame` a lot harder to use

---

*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDY9iXZVKQCnmMj7VcP:1738613095) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
I think it mirrored an `is_global` Rust function that was unstable at the time, so it may be safe to remote it from here. We're using this function to only add global addresses to bootstrap cache.

---

*[src/service.rs, line 631 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDYAXTcaFMyXFxsoC2W:-KDYAXTdM6Ssir3cQ48_:-197735688) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/service.rs#L631)):*
this looks very unclean to me. why not gather the result as a variable whose name starts with `_` in case you're doing this just because the lints complained?

or maybe better, create a function that instantiates a `Service` and wraps it into a struct containing the relevant data.

---

*[src/udp_listener.rs, line 161 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDYCvlR-BPAyqesjaRX:-KDYCvlSQgYaqyun3G0C:456370097) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/udp_listener.rs#L161)):*
mention uTP here, as it is more specific and may help debug problems faster

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
*[src/service.rs, line 631 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDYAXTcaFMyXFxsoC2W:-KDYDfu7yhAjFFLKbNIZ:-1929537624) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/service.rs#L631)):*
It is unclean, but it's only for tests. Nowhere in the tests do we explicitly use that channel but if we don't keep it alive then the tests fail.

If you like, I can instead instead return the channel from `get_event_sender` then assign it to a `_category_rx` everywhere it's used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYF0EZCx1maVGkDFfu:-881005963) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
Should I remove it right now? There's a few little utility functions like this around the place that aren't currently being used but were obviously written for a reason. I slapped `#[allow(unused)]`on the ones that I can imagine being used in the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by vinipsmaker** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYFXGVXDSVuUdAUg5n:-1999793095) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
Go for it.

---

*[src/service.rs, line 631 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDYAXTcaFMyXFxsoC2W:-KDYF8PslNeeVsHafs0n:1646067415) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/service.rs#L631)):*
> If you like, I can instead instead return the channel from `get_event_sender` then assign it to a `_category_rx` everywhere it's used.

I prefer that approach.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYGCmGVAEhGJhPlWRs:-901010367) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
How about `peer_id::get_pub_key` and `Connection::get_protocol`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYGfKW3nXt29NlkMLO:-688311199) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
Or the other stuff in ip_info.rs that hasn't been stabilised upstream?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by vinipsmaker** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYHAgcw7xB9QbweJ_q:1970508262) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
> How about `peer_id::get_pub_key` and `Connection::get_protocol`?

I think they were requested by the routing guys, but I don't remember why. I'd vote for removal and we can add back later if requested. But I'll leave it for you if you want to do in this PR or in another.

> Or the other stuff in ip_info.rs that hasn't been stabilised upstream?

If it's not used, I think it should be removed. By the moment we might need it, it might be in stable Rust anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
*[src/ip_info.rs, line 29 \[r3\]](https://reviewable.io:443/reviews/maidsafe/crust/621#-KDY9iXY-J4y-Yo54-z6:-KDYJfBSA3y4vE-K43CG:474539728) ([raw file](https://github.com/maidsafe/crust/blob/7d66792f0e58dbdc1b60826c197aa7dac4fbf391/src/ip_info.rs#L29)):*
I've removed them in this PR :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by vinipsmaker** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/crust/621)*

**Comment by canndrew** [comment]
And now we wait for AppVeyor...

**Pull request merged**
